### PR TITLE
#349: No support for 'ssl_cert_reqs=ssl.CERT_NONE' parameter which is…

### PR DESCRIPTION
**Pull request by amandeep1991**
… present in pymongo

### CODE REVIEW

**Comment by amandeep1991** [comment]
If this will get merged, I would be able to use the latest version in my project directly without tweaking around the downloaded binaries.  So I am requesting to please let me know if any further changes needs to be done in this PR or if all is fine, kindly merge it on priority.

Also please share the version which includes this change, so that I will update my requirements.txt accordingly.

**Comment by amandeep1991** [comment]
Do I need to make any further changes on this?

**Comment by nesdis** [comment]
Sorry for the delayed response. But with the latest API changes, this fix will no longer be necessary

**Comment by amandeep1991** [comment]
> Sorry for the delayed response. But with the latest API changes, this fix will no longer be necessary

Are you talking about the 'Commits on Jun 02, 2018': Add SSL support and read preference (#114)? If yes, when are you planning for the next release?

Also, please close the PR as it is not required now.

Thanks,
Aman

**Comment by SinxRofozoteron** [comment]
Was support for ssl_cert_reqs added? PyMongo documentation says: by default, PyMongo is configured to require a certificate from the server. To disable this requirement pass ssl.CERT_NONE.
It looks like it is vital parameter to have.
I get an SSL error while trying to connect to Atlas DB instance. I tried to use mongoengine and ssl.CERT_NONE solved the problem. Would be nice to have the same opportunity with Djongo.

**Comment by nesdis** [comment]
all client specific settings are passed defined under 'CLIENT'

**Pull request closed without merging**
