### PR TITLE
*IMPORTANT* SUPPORT LATEST DJANGO: UNFINISHED BUSINESS

### PR DESCRIPTION
**Pull request by johndoe434**
update Django in setup.py

### CODE REVIEW

**Comment by mosi-kha** [comment]
@johndoe434 djongo is not compatible with sqlparse> 0.2.4, especially in migrations.

**Comment by mosi-kha** [comment]
any activity?
@johndoe434 @nesdis

**Comment by johndoe434** [comment]
Working on it

**Comment by nesdis** [comment]
The version of supported Django will be limited in the stable release.

**Pull request closed without merging**
